return function(c, hl)
  hl("AerialNormal", { fg = c.on_surface, bg = c.surface_low })
  hl("AerialNormalNC", { fg = c.on_surface_variant, bg = c.surface_low })
  hl("AerialLine", { fg = c.on_primary_container, bg = c.primary_container, bold = true })
  hl("AerialGuide", { fg = c.outline_variant })

  -- Icon overrides matching editor style
  hl("AerialFileIcon", { fg = c.on_surface })
  hl("AerialModuleIcon", { fg = c.on_surface_variant })
  hl("AerialNamespaceIcon", { fg = c.on_surface_variant })
  hl("AerialPackageIcon", { fg = c.on_surface_variant })
  hl("AerialClassIcon", { fg = c.primary })
  hl("AerialMethodIcon", { fg = c.secondary })
  hl("AerialPropertyIcon", { fg = c.tertiary })
  hl("AerialFieldIcon", { fg = c.tertiary })
  hl("AerialConstructorIcon", { fg = c.primary })
  hl("AerialEnumIcon", { fg = c.primary })
  hl("AerialInterfaceIcon", { fg = c.primary })
  hl("AerialFunctionIcon", { fg = c.secondary })
  hl("AerialVariableIcon", { fg = c.on_surface })
  hl("AerialConstantIcon", { fg = c.tertiary, bold = true })
  hl("AerialStringIcon", { fg = c.tertiary })
  hl("AerialNumberIcon", { fg = c.secondary })
  hl("AerialBooleanIcon", { fg = c.primary, bold = true })
  hl("AerialArrayIcon", { fg = c.on_surface_variant })
  hl("AerialObjectIcon", { fg = c.on_surface_variant })
  hl("AerialKeyIcon", { fg = c.primary })
  hl("AerialNullIcon", { fg = c.primary })
  hl("AerialEnumMemberIcon", { fg = c.tertiary })
  hl("AerialStructIcon", { fg = c.primary })
  hl("AerialEventIcon", { fg = c.secondary })
  hl("AerialOperatorIcon", { fg = c.secondary })
  hl("AerialTypeParameterIcon", { fg = c.primary })
end
