return function(c, hl)
  hl("barbecue_normal", { fg = c.on_surface_variant, bg = nil })
  hl("barbecue_ellipsis", { fg = c.outline, bg = nil })
  hl("barbecue_separator", { fg = c.outline_variant, bg = nil })
  hl("barbecue_modified", { fg = c.secondary, bg = nil })
  hl("barbecue_context", { fg = c.on_surface_variant, bg = nil })

  -- Context item types
  hl("barbecue_context_file", { fg = c.on_surface, bg = nil })
  hl("barbecue_context_module", { fg = c.on_surface_variant, bg = nil })
  hl("barbecue_context_namespace", { fg = c.on_surface_variant, bg = nil })
  hl("barbecue_context_package", { fg = c.on_surface_variant, bg = nil })
  hl("barbecue_context_class", { fg = c.primary, bg = nil })
  hl("barbecue_context_method", { fg = c.secondary, bg = nil })
  hl("barbecue_context_property", { fg = c.tertiary, bg = nil })
  hl("barbecue_context_field", { fg = c.tertiary, bg = nil })
  hl("barbecue_context_constructor", { fg = c.primary, bg = nil })
  hl("barbecue_context_enum", { fg = c.primary, bg = nil })
  hl("barbecue_context_interface", { fg = c.primary, bg = nil })
  hl("barbecue_context_function", { fg = c.secondary, bg = nil })
  hl("barbecue_context_variable", { fg = c.on_surface, bg = nil })
  hl("barbecue_context_constant", { fg = c.tertiary, bg = nil, bold = true })
  hl("barbecue_context_string", { fg = c.tertiary, bg = nil })
  hl("barbecue_context_number", { fg = c.secondary, bg = nil })
  hl("barbecue_context_boolean", { fg = c.primary, bg = nil, bold = true })
  hl("barbecue_context_array", { fg = c.on_surface_variant, bg = nil })
  hl("barbecue_context_object", { fg = c.on_surface_variant, bg = nil })
  hl("barbecue_context_key", { fg = c.primary, bg = nil })
  hl("barbecue_context_null", { fg = c.primary, bg = nil })
  hl("barbecue_context_enum_member", { fg = c.tertiary, bg = nil })
  hl("barbecue_context_struct", { fg = c.primary, bg = nil })
  hl("barbecue_context_event", { fg = c.secondary, bg = nil })
  hl("barbecue_context_operator", { fg = c.secondary, bg = nil })
  hl("barbecue_context_type_parameter", { fg = c.primary, bg = nil })
end
