return function(c, hl)
  hl("BlinkCmpMenu", { fg = c.on_surface, bg = c.surface_container })
  hl("BlinkCmpMenuBorder", { fg = c.primary, bg = c.surface_container })
  hl("BlinkCmpMenuSelection", { fg = c.on_primary_container, bg = c.primary_container })
  hl("BlinkCmpScrollBarThumb", { bg = c.primary_container })
  hl("BlinkCmpScrollBarGutter", { bg = c.surface_high })
  hl("BlinkCmpLabel", { fg = c.on_surface })
  hl("BlinkCmpLabelDeprecated", { fg = c.outline, strikethrough = true })
  hl("BlinkCmpLabelMatch", { fg = c.primary, bold = true })
  hl("BlinkCmpLabelDetail", { fg = c.outline })
  hl("BlinkCmpLabelDescription", { fg = c.outline })
  hl("BlinkCmpKind", { fg = c.secondary })
  hl("BlinkCmpKindClass", { fg = c.primary })
  hl("BlinkCmpKindColor", { fg = c.tertiary })
  hl("BlinkCmpKindConstant", { fg = c.tertiary })
  hl("BlinkCmpKindConstructor", { fg = c.primary })
  hl("BlinkCmpKindEnum", { fg = c.primary })
  hl("BlinkCmpKindEnumMember", { fg = c.tertiary })
  hl("BlinkCmpKindEvent", { fg = c.primary })
  hl("BlinkCmpKindField", { fg = c.secondary })
  hl("BlinkCmpKindFile", { fg = c.outline })
  hl("BlinkCmpKindFolder", { fg = c.primary })
  hl("BlinkCmpKindFunction", { fg = c.secondary })
  hl("BlinkCmpKindInterface", { fg = c.primary_container })
  hl("BlinkCmpKindKeyword", { fg = c.tertiary })
  hl("BlinkCmpKindMethod", { fg = c.tertiary })
  hl("BlinkCmpKindModule", { fg = c.on_surface_variant })
  hl("BlinkCmpKindOperator", { fg = c.secondary })
  hl("BlinkCmpKindProperty", { fg = c.tertiary })
  hl("BlinkCmpKindReference", { fg = c.primary })
  hl("BlinkCmpKindSnippet", { fg = c.on_surface_variant })
  hl("BlinkCmpKindStruct", { fg = c.primary })
  hl("BlinkCmpKindText", { fg = c.on_surface_variant })
  hl("BlinkCmpKindTypeParameter", { fg = c.secondary })
  hl("BlinkCmpKindUnit", { fg = c.tertiary })
  hl("BlinkCmpKindValue", { fg = c.secondary })
  hl("BlinkCmpKindVariable", { fg = c.primary })
  hl("BlinkCmpDoc", { fg = c.on_surface, bg = c.surface_container })
  hl("BlinkCmpDocBorder", { fg = c.outline_variant, bg = c.surface_container })
  hl("BlinkCmpDocSeparator", { fg = c.outline_variant, bg = c.surface_container })
  hl("BlinkCmpDocCursorLine", { bg = c.surface_high })
  hl("BlinkCmpSignatureHelp", { fg = c.on_surface, bg = c.surface_container })
  hl("BlinkCmpSignatureHelpBorder", { fg = c.outline_variant, bg = c.surface_container })
  hl("BlinkCmpSignatureHelpActiveParameter", { fg = c.primary, bold = true, underline = true })
end
