return function(c, hl)
  hl("BufferLineBackground", { fg = c.outline, bg = c.surface_low })
  hl("BufferLineFill", { bg = c.surface_low })
  hl("BufferLineBufferSelected", { fg = c.on_surface, bg = c.surface_high, bold = true })
  hl("BufferLineBufferVisible", { fg = c.on_surface_variant, bg = c.surface_container })
  hl("BufferLineModified", { fg = c.tertiary, bg = c.surface_low })
  hl("BufferLineModifiedSelected", { fg = c.tertiary, bg = c.surface_high })
  hl("BufferLineModifiedVisible", { fg = c.tertiary, bg = c.surface_container })
  hl("BufferLineIndicatorSelected", { fg = c.primary, bg = c.surface_high })
  hl("BufferLineSeparator", { fg = c.outline_variant, bg = c.surface_low })
  hl("BufferLineSeparatorSelected", { fg = c.outline_variant, bg = c.surface_high })
  hl("BufferLineTab", { fg = c.outline, bg = c.surface_low })
  hl("BufferLineTabSelected", { fg = c.primary, bg = c.surface_high, bold = true })
  hl("BufferLineTabSeparator", { fg = c.outline_variant, bg = c.surface_low })
  hl("BufferLineTabSeparatorSelected", { fg = c.primary, bg = c.surface_high })
  hl("BufferLineCloseButton", { fg = c.outline, bg = c.surface_low })
  hl("BufferLineCloseButtonSelected", { fg = c.error, bg = c.surface_high })
  hl("BufferLineError", { fg = c.error, bg = c.surface_low })
  hl("BufferLineErrorSelected", { fg = c.error, bg = c.surface_high, bold = true })
  hl("BufferLineWarning", { fg = c.tertiary, bg = c.surface_low })
  hl("BufferLineWarningSelected", { fg = c.tertiary, bg = c.surface_high, bold = true })
  hl("BufferLineInfo", { fg = c.secondary, bg = c.surface_low })
  hl("BufferLineInfoSelected", { fg = c.secondary, bg = c.surface_high, bold = true })
  hl("BufferLineHint", { fg = c.primary, bg = c.surface_low })
  hl("BufferLineHintSelected", { fg = c.primary, bg = c.surface_high, bold = true })
  hl("BufferLineDiagnostic", { fg = c.outline, bg = c.surface_low })
  hl("BufferLineDiagnosticSelected", { fg = c.outline, bg = c.surface_high })
  hl("BufferLineNumbers", { fg = c.outline, bg = c.surface_low })
  hl("BufferLineNumbersSelected", { fg = c.primary, bg = c.surface_high, bold = true })
  hl("BufferLinePick", { fg = c.error, bg = c.surface_low, bold = true })
  hl("BufferLinePickSelected", { fg = c.error, bg = c.surface_high, bold = true })
  hl("BufferLineGroupSeparator", { fg = c.outline_variant, bg = c.surface_low })
  hl("BufferLineGroupLabel", { fg = c.primary, bg = c.surface_container })
  hl("BufferLineOffsetSeparator", { fg = c.outline_variant, bg = c.surface_low })
  hl("BufferLineTruncMarker", { fg = c.outline, bg = c.surface_low })
end
