return function(c, hl)
  hl("CmpItemAbbr", { fg = c.on_surface })
  hl("CmpItemAbbrDeprecated", { fg = c.outline, strikethrough = true })
  hl("CmpItemAbbrMatch", { fg = c.primary, bold = true })
  hl("CmpItemAbbrMatchFuzzy", { fg = c.primary, bold = true })
  hl("CmpItemKind", { fg = c.on_surface_variant })
  hl("CmpItemMenu", { fg = c.outline })

  -- Custom highlight groups for each type of completions
  hl("CmpItemKindText", { fg = c.on_surface_variant })
  hl("CmpItemKindMethod", { fg = c.secondary })
  hl("CmpItemKindFunction", { fg = c.secondary })
  hl("CmpItemKindConstructor", { fg = c.primary })
  hl("CmpItemKindField", { fg = c.tertiary })
  hl("CmpItemKindVariable", { fg = c.on_surface })
  hl("CmpItemKindClass", { fg = c.primary })
  hl("CmpItemKindInterface", { fg = c.primary })
  hl("CmpItemKindModule", { fg = c.on_surface_variant })
  hl("CmpItemKindProperty", { fg = c.tertiary })
  hl("CmpItemKindUnit", { fg = c.secondary })
  hl("CmpItemKindValue", { fg = c.secondary })
  hl("CmpItemKindEnum", { fg = c.primary })
  hl("CmpItemKindKeyword", { fg = c.primary, bold = true })
  hl("CmpItemKindSnippet", { fg = c.tertiary })
  hl("CmpItemKindColor", { fg = c.tertiary })
  hl("CmpItemKindFile", { fg = c.primary })
  hl("CmpItemKindReference", { fg = c.secondary })
  hl("CmpItemKindFolder", { fg = c.primary })
  hl("CmpItemKindEnumMember", { fg = c.tertiary })
  hl("CmpItemKindConstant", { fg = c.tertiary, bold = true })
  hl("CmpItemKindStruct", { fg = c.primary })
  hl("CmpItemKindEvent", { fg = c.secondary })
  hl("CmpItemKindOperator", { fg = c.secondary })
  hl("CmpItemKindTypeParameter", { fg = c.primary })
end
