return function(c, hl)
  hl("DiffviewFilePanelTitle", { fg = c.primary, bold = true })
  hl("DiffviewFilePanelCounter", { fg = c.secondary, bold = true })
  hl("DiffviewFilePanelFileName", { fg = c.on_surface })
  hl("DiffviewFilePanelPath", { fg = c.outline })
  hl("DiffviewFilePanelInsert", { fg = c.git_added })
  hl("DiffviewFilePanelDelete", { fg = c.git_deleted })
  hl("DiffviewFilePanelConflict", { fg = c.error, bold = true })

  hl("DiffviewStatusAdded", { fg = c.git_added })
  hl("DiffviewStatusModified", { fg = c.git_modified })
  hl("DiffviewStatusDeleted", { fg = c.git_deleted })
  hl("DiffviewStatusRenamed", { fg = c.secondary })
  hl("DiffviewStatusTypeChange", { fg = c.tertiary })
  hl("DiffviewStatusUnmerged", { fg = c.error })
  hl("DiffviewStatusUnknown", { fg = c.outline })

  hl("DiffviewPrimary", { fg = c.primary })
  hl("DiffviewSecondary", { fg = c.secondary })
end
