return function(c, hl)
  -- fzf-lua
  hl("FzfLuaNormal", { fg = c.on_surface, bg = c.surface_container })
  hl("FzfLuaBorder", { fg = c.primary, bg = c.surface_container })
  hl("FzfLuaTitle", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("FzfLuaPreviewNormal", { fg = c.on_surface, bg = c.surface_container })
  hl("FzfLuaPreviewBorder", { fg = c.outline_variant, bg = c.surface_container })
  hl("FzfLuaPreviewTitle", { fg = c.on_primary_container, bg = c.primary_container, bold = true })
  hl("FzfLuaCursorLine", { bg = c.primary_container })
  hl("FzfLuaCursorLineNr", { fg = c.primary, bg = c.primary_container })
  hl("FzfLuaSearch", { fg = c.primary, bold = true })
  hl("FzfLuaBufName", { fg = c.primary })
  hl("FzfLuaBufNr", { fg = c.outline })
  hl("FzfLuaBufFlagCur", { fg = c.primary })
  hl("FzfLuaBufFlagAlt", { fg = c.secondary })
  hl("FzfLuaTabTitle", { fg = c.primary, bold = true })
  hl("FzfLuaTabMarker", { fg = c.primary })
  hl("FzfLuaPathColNr", { fg = c.outline })
  hl("FzfLuaPathLineNr", { fg = c.outline })
  hl("FzfLuaLiveSym", { fg = c.primary, bold = true })
  hl("FzfLuaHeaderBind", { fg = c.secondary, bold = true })
  hl("FzfLuaHeaderText", { fg = c.on_surface_variant })
end
