return function(c, hl)
  -- ── LSP semantic tokens ────────────────────────────────────────

  hl("@lsp.type.class", { fg = c.primary })
  hl("@lsp.type.comment", { fg = c.outline, italic = true })
  hl("@lsp.type.decorator", { fg = c.secondary })
  hl("@lsp.type.enum", { fg = c.primary })
  hl("@lsp.type.enumMember", { fg = c.tertiary, bold = true })
  hl("@lsp.type.event", { fg = c.primary })
  hl("@lsp.type.function", { fg = c.secondary })
  hl("@lsp.type.interface", { fg = c.primary_container })
  hl("@lsp.type.keyword", { fg = c.primary, bold = true })
  hl("@lsp.type.macro", { fg = c.secondary, bold = true })
  hl("@lsp.type.method", { fg = c.tertiary })
  hl("@lsp.type.modifier", { fg = c.primary })
  hl("@lsp.type.namespace", { fg = c.on_surface_variant })
  hl("@lsp.type.number", { fg = c.secondary })
  hl("@lsp.type.operator", { fg = c.secondary })
  hl("@lsp.type.parameter", { fg = c.on_surface_variant })
  hl("@lsp.type.property", { fg = c.tertiary })
  hl("@lsp.type.regexp", { fg = c.tertiary })
  hl("@lsp.type.string", { fg = c.tertiary, italic = true })
  hl("@lsp.type.struct", { fg = c.primary })
  hl("@lsp.type.type", { fg = c.primary })
  hl("@lsp.type.typeParameter", { fg = c.secondary })
  hl("@lsp.type.variable", { fg = c.on_surface })

  hl("@lsp.mod.deprecated", { strikethrough = true })
  hl("@lsp.mod.readonly", { italic = true })
  hl("@lsp.mod.static", { bold = true })
  hl("@lsp.mod.defaultLibrary", { italic = true })
  hl("@lsp.mod.documentation", { italic = true })

  -- ── LSP diagnostic UI ──────────────────────────────────────────

  hl("DiagnosticError", { fg = c.error })
  hl("DiagnosticWarn", { fg = c.tertiary })
  hl("DiagnosticInfo", { fg = c.secondary })
  hl("DiagnosticHint", { fg = c.primary })
  hl("DiagnosticOk", { fg = c.git_added })

  hl("DiagnosticUnderlineError", { undercurl = true, sp = c.error })
  hl("DiagnosticUnderlineWarn", { undercurl = true, sp = c.tertiary })
  hl("DiagnosticUnderlineInfo", { undercurl = true, sp = c.secondary })
  hl("DiagnosticUnderlineHint", { undercurl = true, sp = c.primary })

  hl("DiagnosticVirtualTextError", { fg = c.error, bg = c.surface_high, italic = true })
  hl("DiagnosticVirtualTextWarn", { fg = c.tertiary, bg = c.surface_high, italic = true })
  hl("DiagnosticVirtualTextInfo", { fg = c.secondary, bg = c.surface_high, italic = true })
  hl("DiagnosticVirtualTextHint", { fg = c.primary, bg = c.surface_high, italic = true })

  hl("DiagnosticSignError", { fg = c.error })
  hl("DiagnosticSignWarn", { fg = c.tertiary })
  hl("DiagnosticSignInfo", { fg = c.secondary })
  hl("DiagnosticSignHint", { fg = c.primary })

  hl("DiagnosticFloatingError", { fg = c.error, bg = c.surface_container })
  hl("DiagnosticFloatingWarn", { fg = c.tertiary, bg = c.surface_container })
  hl("DiagnosticFloatingInfo", { fg = c.secondary, bg = c.surface_container })
  hl("DiagnosticFloatingHint", { fg = c.primary, bg = c.surface_container })

  hl("LspReferenceText", { bg = c.surface_high })
  hl("LspReferenceRead", { bg = c.surface_high })
  hl("LspReferenceWrite", { bg = c.primary_container, underline = true })
  hl("LspInlayHint", { fg = c.outline, bg = c.surface_high, italic = true })
  hl("LspCodeLens", { fg = c.outline, italic = true })
  hl("LspCodeLensSeparator", { fg = c.outline_variant })
  hl("LspSignatureActiveParameter", { fg = c.primary, bold = true, underline = true })
end
