return function(c, hl)
  hl("MasonHeader", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("MasonHighlight", { fg = c.primary })
  hl("MasonHighlightBlock", { fg = c.on_primary, bg = c.primary })
  hl("MasonHighlightBlockBold", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("MasonHighlightSecondary", { fg = c.secondary })
  hl("MasonMuted", { fg = c.outline })
  hl("MasonMutedBlock", { fg = c.outline, bg = c.surface_high })
  hl("MasonMutedBlockBold", { fg = c.outline, bg = c.surface_high, bold = true })
  hl("MasonError", { fg = c.error })
end
