return function(c, hl)
  hl("NoiceCmdline", { fg = c.on_surface, bg = c.surface_container })
  hl("NoiceCmdlineIcon", { fg = c.primary })
  hl("NoiceCmdlineIconSearch", { fg = c.secondary })
  hl("NoiceCmdlinePopup", { fg = c.on_surface, bg = c.surface_container })
  hl("NoiceCmdlinePopupBorder", { fg = c.primary, bg = c.surface_container })
  hl("NoiceCmdlinePopupBorderSearch", { fg = c.secondary, bg = c.surface_container })
  hl("NoiceCmdlinePrompt", { fg = c.primary, bold = true })
  hl("NoiceConfirm", { fg = c.on_surface, bg = c.surface_container })
  hl("NoiceConfirmBorder", { fg = c.primary, bg = c.surface_container })
  hl("NoiceFormatConfirm", { fg = c.on_primary_container, bg = c.primary_container })
  hl("NoiceFormatConfirmDefault", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("NoiceFormatDate", { fg = c.outline })
  hl("NoiceFormatEvent", { fg = c.outline })
  hl("NoiceFormatKind", { fg = c.secondary })
  hl("NoiceFormatLevelDebug", { fg = c.outline })
  hl("NoiceFormatLevelError", { fg = c.error })
  hl("NoiceFormatLevelInfo", { fg = c.secondary })
  hl("NoiceFormatLevelOff", { fg = c.outline_variant })
  hl("NoiceFormatLevelTrace", { fg = c.outline_variant })
  hl("NoiceFormatLevelWarn", { fg = c.tertiary })
  hl("NoiceFormatProgressDone", { fg = c.on_primary, bg = c.primary })
  hl("NoiceFormatProgressTodo", { fg = c.primary, bg = c.surface_container })
  hl("NoiceFormatTitle", { fg = c.primary, bold = true })
  hl("NoiceLspProgressClient", { fg = c.primary, bold = true })
  hl("NoiceLspProgressSpinner", { fg = c.secondary })
  hl("NoiceLspProgressTitle", { fg = c.on_surface_variant })
  hl("NoiceMini", { fg = c.on_surface_variant, bg = c.surface_container })
  hl("NoicePopup", { fg = c.on_surface, bg = c.surface_container })
  hl("NoicePopupBorder", { fg = c.outline_variant, bg = c.surface_container })
  hl("NoicePopupmenu", { fg = c.on_surface, bg = c.surface_container })
  hl("NoicePopupmenuBorder", { fg = c.primary, bg = c.surface_container })
  hl("NoicePopupmenuMatch", { fg = c.primary, bold = true })
  hl("NoicePopupmenuSelected", { fg = c.on_primary_container, bg = c.primary_container })
  hl("NoiceScrollbar", { bg = c.surface_high })
  hl("NoiceScrollbarThumb", { bg = c.primary_container })
  hl("NoiceSplit", { fg = c.on_surface, bg = nil })
  hl("NoiceSplitBorder", { fg = c.outline_variant, bg = nil })
  hl("NoiceVirtualText", { fg = c.outline, italic = true })
end
