return function(c, hl)
  -- render-markdown
  hl("RenderMarkdownH1", { fg = c.primary, bold = true })
  hl("RenderMarkdownH2", { fg = c.secondary, bold = true })
  hl("RenderMarkdownH3", { fg = c.tertiary, bold = true })
  hl("RenderMarkdownH4", { fg = c.on_surface_variant, bold = true })
  hl("RenderMarkdownH5", { fg = c.outline, bold = true })
  hl("RenderMarkdownH6", { fg = c.outline_variant, bold = true })
  hl("RenderMarkdownH1Bg", { bg = c.primary_container })
  hl("RenderMarkdownH2Bg", { bg = c.surface_high })
  hl("RenderMarkdownH3Bg", { bg = c.surface_high })
  hl("RenderMarkdownH4Bg", { bg = c.surface_high })
  hl("RenderMarkdownH5Bg", { bg = c.surface_high })
  hl("RenderMarkdownH6Bg", { bg = c.surface_high })
  hl("RenderMarkdownCode", { bg = c.surface_high })
  hl("RenderMarkdownCodeInline", { fg = c.tertiary, bg = c.surface_high })
  hl("RenderMarkdownBullet", { fg = c.primary })
  hl("RenderMarkdownQuote", { fg = c.outline, italic = true })
  hl("RenderMarkdownDash", { fg = c.outline_variant })
  hl("RenderMarkdownLink", { fg = c.primary, underline = true })
  hl("RenderMarkdownWikiLink", { fg = c.primary, underline = true })
  hl("RenderMarkdownHighlight", { bg = c.primary_container })
  hl("RenderMarkdownChecked", { fg = c.git_added })
  hl("RenderMarkdownUnchecked", { fg = c.outline })
  hl("RenderMarkdownTableHead", { fg = c.primary, bold = true })
  hl("RenderMarkdownTableRow", { fg = c.on_surface })
  hl("RenderMarkdownTableFill", { fg = c.outline_variant })
  hl("RenderMarkdownSuccess", { fg = c.git_added })
  hl("RenderMarkdownInfo", { fg = c.secondary })
  hl("RenderMarkdownHint", { fg = c.primary })
  hl("RenderMarkdownWarn", { fg = c.tertiary })
  hl("RenderMarkdownError", { fg = c.error })
end
