return function(c, hl)
  hl("SnacksNormal", { fg = c.on_surface, bg = c.surface_container })
  hl("SnacksNormalNC", { fg = c.on_surface_variant, bg = c.surface_container })
  hl("SnacksBorder", { fg = c.outline_variant, bg = c.surface_container })
  hl("SnacksBackdrop", { bg = c.surface, blend = 40 })
  hl("SnacksDashboardNormal", { fg = c.on_surface, bg = nil })
  hl("SnacksDashboardDesc", { fg = c.on_surface_variant })
  hl("SnacksDashboardFile", { fg = c.primary })
  hl("SnacksDashboardDir", { fg = c.outline })
  hl("SnacksDashboardFooter", { fg = c.outline, italic = true })
  hl("SnacksDashboardHeader", { fg = c.primary, bold = true })
  hl("SnacksDashboardIcon", { fg = c.primary })
  hl("SnacksDashboardKey", { fg = c.secondary, bold = true })
  hl("SnacksDashboardSpecial", { fg = c.tertiary })
  hl("SnacksDashboardTitle", { fg = c.primary, bold = true })
  hl("SnacksNotifierBorderError", { fg = c.error })
  hl("SnacksNotifierBorderWarn", { fg = c.tertiary })
  hl("SnacksNotifierBorderInfo", { fg = c.secondary })
  hl("SnacksNotifierBorderDebug", { fg = c.outline })
  hl("SnacksNotifierBorderTrace", { fg = c.outline_variant })
  hl("SnacksNotifierIconError", { fg = c.error })
  hl("SnacksNotifierIconWarn", { fg = c.tertiary })
  hl("SnacksNotifierIconInfo", { fg = c.secondary })
  hl("SnacksNotifierIconDebug", { fg = c.outline })
  hl("SnacksNotifierIconTrace", { fg = c.outline_variant })
  hl("SnacksNotifierTitleError", { fg = c.error, bold = true })
  hl("SnacksNotifierTitleWarn", { fg = c.tertiary, bold = true })
  hl("SnacksNotifierTitleInfo", { fg = c.secondary, bold = true })
  hl("SnacksNotifierTitleDebug", { fg = c.outline, bold = true })
  hl("SnacksNotifierTitleTrace", { fg = c.outline_variant, bold = true })
  hl("SnacksPickerBorder", { fg = c.primary, bg = c.surface_container })
  hl("SnacksPickerTitle", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("SnacksPickerMatch", { fg = c.primary, bold = true })
  hl("SnacksPickerSelected", { fg = c.tertiary })
  hl("SnacksPickerDir", { fg = c.outline })
  hl("SnacksPickerFile", { fg = c.on_surface })
  hl("SnacksPickerPathHidden", { fg = c.outline_variant })
  hl("SnacksPickerToggle", { fg = c.secondary, bold = true })
  hl("SnacksPickerListCursorLine", { bg = c.primary_container })
  hl("SnacksPickerPreviewCursorLine", { bg = c.surface_high })
  hl("SnacksIndent", { fg = c.outline_variant })
  hl("SnacksIndentScope", { fg = c.primary })
  hl("SnacksZenBar", { fg = c.outline_variant, bg = nil })
  hl("SnacksScrollbar", { fg = c.primary_container })
  hl("SnacksInputNormal", { fg = c.on_surface, bg = c.surface_high })
  hl("SnacksInputBorder", { fg = c.primary, bg = c.surface_high })
  hl("SnacksInputTitle", { fg = c.on_primary, bg = c.primary })
  hl("SnacksProfilerBadgeHl", { fg = c.on_primary, bg = c.primary })
end
