return function(c, hl)
  hl("Comment", { fg = c.outline, italic = true })
  hl("Constant", { fg = c.tertiary })
  hl("String", { fg = c.tertiary, italic = true })
  hl("Character", { fg = c.tertiary })
  hl("Number", { fg = c.secondary })
  hl("Boolean", { fg = c.primary, bold = true })
  hl("Float", { fg = c.secondary })
  hl("Identifier", { fg = c.on_surface })
  hl("Function", { fg = c.secondary })
  hl("Statement", { fg = c.primary })
  hl("Conditional", { fg = c.primary })
  hl("Repeat", { fg = c.primary })
  hl("Label", { fg = c.primary })
  hl("Operator", { fg = c.secondary })
  hl("Keyword", { fg = c.primary, bold = true })
  hl("Exception", { fg = c.error })
  hl("PreProc", { fg = c.secondary })
  hl("Include", { fg = c.secondary })
  hl("Define", { fg = c.secondary })
  hl("Macro", { fg = c.secondary })
  hl("PreCondit", { fg = c.secondary })
  hl("Type", { fg = c.primary })
  hl("StorageClass", { fg = c.primary })
  hl("Structure", { fg = c.primary })
  hl("Typedef", { fg = c.primary })
  hl("Special", { fg = c.tertiary })
  hl("SpecialChar", { fg = c.tertiary })
  hl("Tag", { fg = c.primary })
  hl("Delimiter", { fg = c.outline })
  hl("SpecialComment", { fg = c.outline, italic = true })
  hl("Debug", { fg = c.error })
  hl("Underlined", { underline = true })
  hl("Ignore", { fg = c.outline_variant })
  hl("Error", { fg = c.error })
  hl("Todo", { fg = c.on_primary, bg = c.primary, bold = true })

  -- Treesitter @ groups
  hl("@comment", { fg = c.outline, italic = true })
  hl("@comment.documentation", { fg = c.outline, italic = true })
  hl("@comment.error", { fg = c.error, italic = true })
  hl("@comment.warning", { fg = c.tertiary, italic = true })
  hl("@comment.todo", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("@comment.note", { fg = c.on_primary_container, bg = c.primary_container, bold = true })

  hl("@string", { fg = c.tertiary, italic = true })
  hl("@string.regexp", { fg = c.tertiary })
  hl("@string.escape", { fg = c.primary, bold = true })
  hl("@string.special", { fg = c.tertiary })
  hl("@string.special.url", { fg = c.primary, underline = true })
  hl("@string.special.symbol", { fg = c.tertiary })

  hl("@character", { fg = c.tertiary })
  hl("@character.special", { fg = c.primary })

  hl("@boolean", { fg = c.primary, bold = true })
  hl("@number", { fg = c.secondary })
  hl("@number.float", { fg = c.secondary })

  hl("@variable", { fg = c.on_surface })
  hl("@variable.builtin", { fg = c.primary, italic = true })
  hl("@variable.parameter", { fg = c.on_surface_variant })
  hl("@variable.parameter.builtin", { fg = c.primary, italic = true })
  hl("@variable.member", { fg = c.tertiary })

  hl("@constant", { fg = c.tertiary, bold = true })
  hl("@constant.builtin", { fg = c.primary, bold = true })
  hl("@constant.macro", { fg = c.secondary, bold = true })

  hl("@module", { fg = c.on_surface_variant })
  hl("@module.builtin", { fg = c.primary, italic = true })
  hl("@label", { fg = c.primary })

  hl("@function", { fg = c.secondary })
  hl("@function.builtin", { fg = c.secondary, italic = true })
  hl("@function.call", { fg = c.secondary })
  hl("@function.macro", { fg = c.secondary, bold = true })
  hl("@function.method", { fg = c.tertiary })
  hl("@function.method.call", { fg = c.tertiary })

  hl("@constructor", { fg = c.primary })
  hl("@operator", { fg = c.secondary })

  hl("@keyword", { fg = c.primary, bold = true })
  hl("@keyword.coroutine", { fg = c.primary, bold = true })
  hl("@keyword.function", { fg = c.primary, bold = true })
  hl("@keyword.operator", { fg = c.secondary })
  hl("@keyword.import", { fg = c.secondary })
  hl("@keyword.type", { fg = c.primary })
  hl("@keyword.modifier", { fg = c.primary })
  hl("@keyword.repeat", { fg = c.primary, bold = true })
  hl("@keyword.return", { fg = c.primary, bold = true })
  hl("@keyword.debug", { fg = c.error })
  hl("@keyword.exception", { fg = c.error })
  hl("@keyword.conditional", { fg = c.primary, bold = true })
  hl("@keyword.conditional.ternary", { fg = c.secondary })
  hl("@keyword.directive", { fg = c.secondary })
  hl("@keyword.directive.define", { fg = c.secondary })

  hl("@type", { fg = c.primary })
  hl("@type.builtin", { fg = c.primary, italic = true })
  hl("@type.definition", { fg = c.primary })

  hl("@attribute", { fg = c.secondary })
  hl("@attribute.builtin", { fg = c.secondary, italic = true })
  hl("@property", { fg = c.tertiary })

  hl("@punctuation.delimiter", { fg = c.outline })
  hl("@punctuation.bracket", { fg = c.on_surface_variant })
  hl("@punctuation.special", { fg = c.secondary })

  hl("@tag", { fg = c.primary })
  hl("@tag.builtin", { fg = c.primary, italic = true })
  hl("@tag.attribute", { fg = c.tertiary })
  hl("@tag.delimiter", { fg = c.outline })

  hl("@diff.plus", { fg = c.git_added })
  hl("@diff.minus", { fg = c.git_deleted })
  hl("@diff.delta", { fg = c.git_modified })

  hl("@markup.strong", { bold = true })
  hl("@markup.italic", { italic = true })
  hl("@markup.strikethrough", { strikethrough = true })
  hl("@markup.underline", { underline = true })
  hl("@markup.heading", { fg = c.primary, bold = true })
  hl("@markup.heading.1", { fg = c.primary, bold = true })
  hl("@markup.heading.2", { fg = c.secondary, bold = true })
  hl("@markup.heading.3", { fg = c.tertiary, bold = true })
  hl("@markup.heading.4", { fg = c.on_surface_variant, bold = true })
  hl("@markup.heading.5", { fg = c.outline, bold = true })
  hl("@markup.heading.6", { fg = c.outline_variant, bold = true })
  hl("@markup.quote", { fg = c.outline, italic = true })
  hl("@markup.math", { fg = c.tertiary })
  hl("@markup.link", { fg = c.primary, underline = true })
  hl("@markup.link.label", { fg = c.secondary })
  hl("@markup.link.url", { fg = c.primary, underline = true, italic = true })
  hl("@markup.raw", { fg = c.on_surface_variant })
  hl("@markup.raw.block", { fg = c.on_surface_variant })
  hl("@markup.list", { fg = c.primary })
  hl("@markup.list.checked", { fg = c.git_added })
  hl("@markup.list.unchecked", { fg = c.outline })
end
