return function(c, hl)
  hl("TelescopeBorder", { fg = c.primary, bg = c.surface_container })
  hl("TelescopeNormal", { fg = c.on_surface, bg = c.surface_container })
  hl("TelescopeTitle", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("TelescopePromptNormal", { fg = c.on_surface, bg = c.surface_high })
  hl("TelescopePromptBorder", { fg = c.primary, bg = c.surface_high })
  hl("TelescopePromptTitle", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("TelescopePromptPrefix", { fg = c.primary, bg = c.surface_high })
  hl("TelescopePromptCounter", { fg = c.outline, bg = c.surface_high })
  hl("TelescopePreviewNormal", { fg = c.on_surface, bg = c.surface_container })
  hl("TelescopePreviewBorder", { fg = c.outline_variant, bg = c.surface_container })
  hl("TelescopePreviewTitle", { fg = c.on_primary_container, bg = c.primary_container, bold = true })
  hl("TelescopeResultsNormal", { fg = c.on_surface, bg = c.surface_container })
  hl("TelescopeResultsBorder", { fg = c.outline_variant, bg = c.surface_container })
  hl("TelescopeResultsTitle", { fg = c.outline, bg = c.surface_container })
  hl("TelescopeSelection", { fg = c.on_primary_container, bg = c.primary_container })
  hl("TelescopeSelectionCaret", { fg = c.primary, bg = c.primary_container })
  hl("TelescopeMultiSelection", { fg = c.tertiary, bg = c.surface_high })
  hl("TelescopeMultiIcon", { fg = c.tertiary })
  hl("TelescopeMatching", { fg = c.primary, bold = true })
  hl("TelescopeResultsDiffAdd", { fg = c.git_added })
  hl("TelescopeResultsDiffChange", { fg = c.git_modified })
  hl("TelescopeResultsDiffDelete", { fg = c.git_deleted })
  hl("TelescopeResultsDiffUntracked", { fg = c.tertiary })
end
