return function(c, hl)
  hl("TodoBgTODO", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("TodoFgTODO", { fg = c.primary })
  hl("TodoSignTODO", { fg = c.primary })
  hl("TodoBgFIX", { fg = c.surface, bg = c.error, bold = true })
  hl("TodoFgFIX", { fg = c.error })
  hl("TodoSignFIX", { fg = c.error })
  hl("TodoBgWARN", { fg = c.surface, bg = c.tertiary, bold = true })
  hl("TodoFgWARN", { fg = c.tertiary })
  hl("TodoSignWARN", { fg = c.tertiary })
  hl("TodoBgNOTE", { fg = c.on_primary_container, bg = c.primary_container, bold = true })
  hl("TodoFgNOTE", { fg = c.secondary })
  hl("TodoSignNOTE", { fg = c.secondary })
  hl("TodoBgHACK", { fg = c.surface, bg = c.secondary_container, bold = true })
  hl("TodoFgHACK", { fg = c.on_secondary_container })
  hl("TodoSignHACK", { fg = c.on_secondary_container })
  hl("TodoBgPERF", { fg = c.surface, bg = c.tertiary_container, bold = true })
  hl("TodoFgPERF", { fg = c.tertiary })
  hl("TodoSignPERF", { fg = c.tertiary })
  hl("TodoBgTEST", { fg = c.surface, bg = c.secondary, bold = true })
  hl("TodoFgTEST", { fg = c.secondary })
  hl("TodoSignTEST", { fg = c.secondary })
end
