return function(c, hl)
  hl("TroubleNormal", { fg = c.on_surface, bg = nil })
  hl("TroubleNormalNC", { fg = c.on_surface_variant, bg = nil })
  hl("TroubleCount", { fg = c.on_primary_container, bg = c.primary_container })
  hl("TroublePos", { fg = c.outline })
  hl("TroubleLocation", { fg = c.outline })
  hl("TroubleFile", { fg = c.primary, bold = true })
  hl("TroubleSource", { fg = c.outline })
  hl("TroubleCode", { fg = c.outline })
  hl("TroubleText", { fg = c.on_surface })
  hl("TroubleIconError", { fg = c.error })
  hl("TroubleIconWarning", { fg = c.tertiary })
  hl("TroubleIconInformation", { fg = c.secondary })
  hl("TroubleIconHint", { fg = c.primary })
  hl("TroubleIndent", { fg = c.outline_variant })
  hl("TroubleIndentFoldOpen", { fg = c.primary })
  hl("TroubleIndentFoldClosed", { fg = c.outline })
  hl("TroubleFoldIcon", { fg = c.primary })
  hl("TroubleIconDirectory", { fg = c.primary })
  hl("TroubleIconFile", { fg = c.outline })
end
