return function(c, hl)
  -- dressing.nvim
  hl("DressingNormal", { fg = c.on_surface, bg = c.surface_container })
  hl("DressingBorder", { fg = c.primary, bg = c.surface_container })
  hl("DressingTitle", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("DressingInputNormal", { fg = c.on_surface, bg = c.surface_high })
  hl("DressingInputBorder", { fg = c.outline, bg = c.surface_high })

  -- flash.nvim
  hl("FlashBackdrop", { fg = c.outline })
  hl("FlashCurrent", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("FlashLabel", { fg = c.on_primary, bg = c.primary_container, bold = true })
  hl("FlashMatch", { fg = c.primary, bg = c.surface_high })
  hl("FlashPrompt", { fg = c.on_surface, bg = c.surface_container })
  hl("FlashPromptIcon", { fg = c.primary, bg = c.surface_container })
  hl("FlashCursor", { fg = c.on_primary, bg = c.primary })

  -- todo-comments
  hl("TodoBgTODO", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("TodoFgTODO", { fg = c.primary })
  hl("TodoSignTODO", { fg = c.primary })
  hl("TodoBgFIX", { fg = c.surface, bg = c.error, bold = true })
  hl("TodoFgFIX", { fg = c.error })
  hl("TodoSignFIX", { fg = c.error })
  hl("TodoBgWARN", { fg = c.surface, bg = c.tertiary, bold = true })
  hl("TodoFgWARN", { fg = c.tertiary })
  hl("TodoSignWARN", { fg = c.tertiary })
  hl("TodoBgNOTE", { fg = c.on_primary_container, bg = c.primary_container, bold = true })
  hl("TodoFgNOTE", { fg = c.secondary })
  hl("TodoSignNOTE", { fg = c.secondary })
  hl("TodoBgHACK", { fg = c.surface, bg = c.secondary_container, bold = true })
  hl("TodoFgHACK", { fg = c.on_secondary_container })
  hl("TodoSignHACK", { fg = c.on_secondary_container })
  hl("TodoBgPERF", { fg = c.surface, bg = c.tertiary_container, bold = true })
  hl("TodoFgPERF", { fg = c.tertiary })
  hl("TodoSignPERF", { fg = c.tertiary })
  hl("TodoBgTEST", { fg = c.surface, bg = c.secondary, bold = true })
  hl("TodoFgTEST", { fg = c.secondary })
  hl("TodoSignTEST", { fg = c.secondary })

  -- render-markdown
  hl("RenderMarkdownH1", { fg = c.primary, bold = true })
  hl("RenderMarkdownH2", { fg = c.secondary, bold = true })
  hl("RenderMarkdownH3", { fg = c.tertiary, bold = true })
  hl("RenderMarkdownH4", { fg = c.on_surface_variant, bold = true })
  hl("RenderMarkdownH5", { fg = c.outline, bold = true })
  hl("RenderMarkdownH6", { fg = c.outline_variant, bold = true })
  hl("RenderMarkdownH1Bg", { bg = c.primary_container })
  hl("RenderMarkdownH2Bg", { bg = c.surface_high })
  hl("RenderMarkdownH3Bg", { bg = c.surface_high })
  hl("RenderMarkdownH4Bg", { bg = c.surface_high })
  hl("RenderMarkdownH5Bg", { bg = c.surface_high })
  hl("RenderMarkdownH6Bg", { bg = c.surface_high })
  hl("RenderMarkdownCode", { bg = c.surface_high })
  hl("RenderMarkdownCodeInline", { fg = c.tertiary, bg = c.surface_high })
  hl("RenderMarkdownBullet", { fg = c.primary })
  hl("RenderMarkdownQuote", { fg = c.outline, italic = true })
  hl("RenderMarkdownDash", { fg = c.outline_variant })
  hl("RenderMarkdownLink", { fg = c.primary, underline = true })
  hl("RenderMarkdownWikiLink", { fg = c.primary, underline = true })
  hl("RenderMarkdownHighlight", { bg = c.primary_container })
  hl("RenderMarkdownChecked", { fg = c.git_added })
  hl("RenderMarkdownUnchecked", { fg = c.outline })
  hl("RenderMarkdownTableHead", { fg = c.primary, bold = true })
  hl("RenderMarkdownTableRow", { fg = c.on_surface })
  hl("RenderMarkdownTableFill", { fg = c.outline_variant })
  hl("RenderMarkdownSuccess", { fg = c.git_added })
  hl("RenderMarkdownInfo", { fg = c.secondary })
  hl("RenderMarkdownHint", { fg = c.primary })
  hl("RenderMarkdownWarn", { fg = c.tertiary })
  hl("RenderMarkdownError", { fg = c.error })

  -- avante.nvim
  hl("AvanteTitle", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("AvanteReversedTitle", { fg = c.primary, bg = c.surface_container })
  hl("AvanteSubtitle", { fg = c.on_primary_container, bg = c.primary_container })
  hl("AvanteReversedSubtitle", { fg = c.primary_container, bg = c.surface_container })
  hl("AvanteThirdTitle", { fg = c.on_surface_variant, bg = c.surface_high })
  hl("AvanteReversedThirdTitle", { fg = c.surface_high, bg = c.surface_container })
  hl("AvanteConflictCurrent", { bg = c.primary_container })
  hl("AvanteConflictIncoming", { bg = c.tertiary_container })
  hl("AvanteConflictCurrentLabel", { fg = c.on_primary_container, bg = c.primary_container, bold = true })
  hl("AvanteConflictIncomingLabel", { fg = c.tertiary, bg = c.tertiary_container, bold = true })
  hl("AvantePopupHint", { fg = c.outline, italic = true })
  hl("AvanteInlineHint", { fg = c.outline, italic = true })

  -- fzf-lua
  hl("FzfLuaNormal", { fg = c.on_surface, bg = c.surface_container })
  hl("FzfLuaBorder", { fg = c.primary, bg = c.surface_container })
  hl("FzfLuaTitle", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("FzfLuaPreviewNormal", { fg = c.on_surface, bg = c.surface_container })
  hl("FzfLuaPreviewBorder", { fg = c.outline_variant, bg = c.surface_container })
  hl("FzfLuaPreviewTitle", { fg = c.on_primary_container, bg = c.primary_container, bold = true })
  hl("FzfLuaCursorLine", { bg = c.primary_container })
  hl("FzfLuaCursorLineNr", { fg = c.primary, bg = c.primary_container })
  hl("FzfLuaSearch", { fg = c.primary, bold = true })
  hl("FzfLuaBufName", { fg = c.primary })
  hl("FzfLuaBufNr", { fg = c.outline })
  hl("FzfLuaBufFlagCur", { fg = c.primary })
  hl("FzfLuaBufFlagAlt", { fg = c.secondary })
  hl("FzfLuaTabTitle", { fg = c.primary, bold = true })
  hl("FzfLuaTabMarker", { fg = c.primary })
  hl("FzfLuaPathColNr", { fg = c.outline })
  hl("FzfLuaPathLineNr", { fg = c.outline })
  hl("FzfLuaLiveSym", { fg = c.primary, bold = true })
  hl("FzfLuaHeaderBind", { fg = c.secondary, bold = true })
  hl("FzfLuaHeaderText", { fg = c.on_surface_variant })
end
