return function(c, hl)
  hl("WhichKey", { fg = c.primary, bold = true })
  hl("WhichKeyBorder", { fg = c.outline_variant, bg = c.surface_container })
  hl("WhichKeyGroup", { fg = c.secondary })
  hl("WhichKeyDesc", { fg = c.on_surface })
  hl("WhichKeySeparator", { fg = c.outline_variant })
  hl("WhichKeyValue", { fg = c.outline })
  hl("WhichKeyNormal", { fg = c.on_surface, bg = c.surface_container })
  hl("WhichKeyTitle", { fg = c.on_primary, bg = c.primary, bold = true })
  hl("WhichKeyIcon", { fg = c.primary })
  hl("WhichKeyIconBlue", { fg = c.primary })
  hl("WhichKeyIconGreen", { fg = c.git_added })
  hl("WhichKeyIconRed", { fg = c.error })
  hl("WhichKeyIconYellow", { fg = c.tertiary })
  hl("WhichKeyIconPurple", { fg = c.secondary })
  hl("WhichKeyIconCyan", { fg = c.on_secondary_container })
  hl("WhichKeyIconGrey", { fg = c.outline })
end
