name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable

      - name: Install LuaRocks & luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: Run luacheck
        run: luacheck lua/

      - name: Check Lua Syntax
        run: make -f .github/Makefile check-syntax
